In [2]:
pip install pymysql

   ---------------------------------------- 0.0/44.8 kB ? eta -:--:--
   --------- ------------------------------ 10.2/44.8 kB ? eta -:--:--
   ------------------ --------------------- 20.5/44.8 kB 320.0 kB/s eta 0:00:01
   ---------------------------------------- 44.8/44.8 kB 367.3 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
import pymysql

In [17]:
host = ''
user = ''
password = ''
database = ''

# Connect to the MySQL database
connection = pymysql.connect(host=host,
                             user=user,
                             password=password,
                             database=database)

In [18]:
from datetime import datetime, timedelta

In [19]:
end_date = datetime.now()
start_date = end_date - timedelta(days=7)

start_date_str = start_date.strftime('%Y-%m-%d')
end_date_str = end_date.strftime('%Y-%m-%d')

In [20]:
start_date_str

'2024-04-22'

In [21]:
end_date_str

'2024-04-29'

In [22]:
query = f"SELECT date, rate FROM rates WHERE date BETWEEN '{start_date_str}' AND '{end_date_str}'"

In [23]:
cursor = connection.cursor()
cursor.execute(query)
data = cursor.fetchall()

In [24]:
data

((datetime.date(2024, 4, 22), Decimal('57.73')),
 (datetime.date(2024, 4, 23), Decimal('57.84')),
 (datetime.date(2024, 4, 24), Decimal('57.61')),
 (datetime.date(2024, 4, 25), Decimal('57.61')),
 (datetime.date(2024, 4, 26), Decimal('57.36')),
 (datetime.date(2024, 4, 27), Decimal('57.40')),
 (datetime.date(2024, 4, 28), Decimal('57.40')))

In [25]:
cursor.close()
connection.close()

In [26]:
data

((datetime.date(2024, 4, 22), Decimal('57.73')),
 (datetime.date(2024, 4, 23), Decimal('57.84')),
 (datetime.date(2024, 4, 24), Decimal('57.61')),
 (datetime.date(2024, 4, 25), Decimal('57.61')),
 (datetime.date(2024, 4, 26), Decimal('57.36')),
 (datetime.date(2024, 4, 27), Decimal('57.40')),
 (datetime.date(2024, 4, 28), Decimal('57.40')))

In [32]:
import numpy as np

rates = [float(row[1]) for row in data]

rates_array = np.array(rates)

past_columns = []
for i in range(7):
    past_columns.append(f"past_{i}")

preprocessed_data = np.zeros((len(rates) - 6, 7))
for i in range(6, len(rates)):
    preprocessed_data[i - 6] = rates[i-6:i+1][::-1]

In [33]:
preprocessed_data

array([[57.4 , 57.4 , 57.36, 57.61, 57.61, 57.84, 57.73]])

In [3]:
import joblib

model = joblib.load('model.pkl')

In [35]:
predictions = model.predict(preprocessed_data)

C:\Users\Nikola\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MLPRegressor was fitted with feature names
  warnings.warn(


In [36]:
predictions

array([[56.74224514, 56.75664544, 56.76898127, 56.76901942, 56.79742601,
        56.79959797, 56.7943261 ]])

In [6]:
dummy_data = [[59.56, 58.21, 56.12, 57.12, 51.21, 56.89, 55.30]]

In [7]:
predictions_dummy = model.predict(dummy_data)

C:\Users\Nikola\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MLPRegressor was fitted with feature names
  warnings.warn(


In [8]:
predictions_dummy

array([[56.7422262 , 56.75663342, 56.76899566, 56.76901348, 56.79744782,
        56.79960948, 56.79431812]])